# Generated by Django 3.1.6 on 2021-02-03 08:55

import ShipBooking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddRouteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_id', models.IntegerField(default=ShipBooking.models.AddRouteModel.number, unique=True)),
                ('Ship_from', models.CharField(max_length=30)),
                ('Ship_to', models.CharField(max_length=30)),
                ('Journey_time', models.IntegerField()),
                ('Price_per_seat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AddShipModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ship_number', models.IntegerField()),
                ('Start_time', models.TimeField()),
                ('Total_seats', models.IntegerField()),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipBooking.addroutemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=200, null=True)),
                ('Passenger_name', models.CharField(max_length=200, null=True)),
                ('No_of_passengers', models.IntegerField()),
                ('Travel_date', models.DateField()),
                ('Ship_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipBooking.addshipmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AdduserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Phone', models.CharField(max_length=10)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShipBooking.transactions')),
            ],
        ),
    ]
